#
# Makefile for ST-Ericsson CG2900 connectivity combo controller
#

obj-$(CONFIG_MFD_CG2900)	+= cg2900_core.o
export-objs			:= cg2900_core.o

obj-$(CONFIG_MFD_CG2900)	+= cg2900_char_devices.o

obj-$(CONFIG_MFD_CG2900_CHIP)	+= cg2900_chip.o
obj-$(CONFIG_MFD_STLC2690_CHIP)	+= stlc2690_chip.o

obj-$(CONFIG_MFD_CG2900_AUDIO)	+= cg2900_audio.o
